title: PCHH Knowledge 
description: This is the PCHH Knowledge Base - a collection of informative articles about PCs.
theme: just-the-docs
color_scheme: dark

permalink: /:title/

url: https://pchelphub.github.io

aux_links:
  PCHH Discord Server: https://discord.gg/PCHH
