title: PCHH Knowledge 
description: Knowledge and articles about PCs and more!
theme: just-the-docs

permalink: /:title/

url: https://pchelphub.github.io

aux_links:
  PCHH Discord Server: https://discord.gg/PCHH
