title: PCHH Knowledge Base 
description: Helpful knowledge about PCs. 
theme: just-the-docs

permalink: /:title/

url: https://pchelphub.github.io

aux_links:
  PCHH Discord Server: https://discord.gg/PCHH
