title: PCHH Knowledge Base 
description: Helpful knowledge about PCs. 
theme: just-the-docs

url: https://pchelphub.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
